service: service-existing-s35
provider:
  name: aws
  runtime: python3.7
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  ex_s3:
    handler: handler.ex_s3
    layers:
      - arn:aws:lambda:us-east-1:480915327742:layer:pandas-python3-7:2


plugins:
  - serverless-python-requirements
