service: service-existing-s34
provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  sample:
    handler: handler.sample
    layers:
      - arn:aws:lambda:us-east-1:480915327742:layer:pandas-python3-7:2
    events: 
      - s3:
          bucket: adobe-assessment
          event: s3:ObjectCreated:*
          rules:
            - prefix: input-event/
            - suffix: .tabs
          existing: true

# layer:
#   pandas-layer:
#     path: pandas-layer-dir
#     name: pandas-layer
#     retain: true
plugins:
  - serverless-python-requirements
