service: s-RevenueFromSearchEngine
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  rfse:
    handler: src/RevenueFromSearchEngine.main
    layers:
      - arn:aws:lambda:us-east-1:480915327742:layer:pandas-python3-7:2
    events: 
      - s3:
          bucket: adobe-dataengineer
          event: s3:ObjectCreated:*
          rules:
            - prefix: prod/input/
            - suffix: .tab
plugins:
  - serverless-python-requirements
