service: s3-to-lambda-with-layer-actions
provider:
  name: aws
  runtime: python3.7
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_joke_layer_actions:
    handler: handler.get_joke_layer_a
    layers:
      - arn:aws:lambda:us-east-1:480915327742:layer:pandas-python3-7:2
    events: 
      - s3:
          bucket: adobe-assessment-4
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
            - suffix: .tab


plugins:
  - serverless-python-requirements
