service: service-existing-s3
provider:
  name: aws
  runtime: python3.7
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  ex_s3:
    handler: handler.ex_s3
    layers:
      - arn:aws:lambda:us-east-1:480915327742:layer:pandas-python3-7:2
    events: 
      - s3:
          bucket: adobe-assessment-1
          event: s3:ObjectCreated:*
          rules:
            - prefix: input123/
            - suffix: .tab2
          existing: true


plugins:
  - serverless-python-requirements
